# Dependabot configuration file to keep GitHub Actions and Gradle dependencies up to date.

version: 2
updates:


  # Maintain GitHub Actions by checking for updates to workflow steps
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"


  # Maintain Android/Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    # Group related updates to minimize the number of open pull requests
    groups:
      android-internal:
        patterns:
          - "androidx.*"
          - "com.android.*"
          - "org.jetbrains.kotlin.*"
      jackson-stack:
        patterns:
          - "com.fasterxml.jackson.*"
